### ISSUE TITLE
BigEndian support

### ISSUE THREAD

**Issue by tnakaike** [orlandos-nl/BSON#38]
I tried to use this package with MongoKitten on a big endian machine. At that time, I had endian problems. For the master/5.2 branch, I needed some fixes like as follows. Although I plan to make PRs to support big endian, I am wondering to know which branch should be used as the code base. Because, it seems that this package is being re-written in the develop/6.0/rewrite branch.

```
+#if _endian(little)
                 let double: Double = try fromBytes(storage[position..<position+8])
+#else
+                var tmp = Bytes(repeating: 0, count: 8)
+                var j: Int = 0
+                for i in (position ..< position + 8).reversed() {
+                    tmp[j] = storage[i]
+		    j+=1
+		}
+                let double: Double = try fromBytes(tmp)
+#endif
```

**Comment by Joannis** [comment]
For now, definitely 5.2. 6.0 is going to evolve a lot, still.

I think the `#if arch(...)` is preferred over `#if _endian(little)` because the underscore prefixed ones are unstable APIs.

**Comment by tnakaike** [comment]
Sure. Thanks!

**Comment by Joannis** [comment]
What machine are you running Swift on? I didn't know swift ran on big endian systems.

**Comment by tnakaike** [comment]
Hi Joannis, Thank you for your response.

I am running Swift on an IBM mainframe 😃.
https://www.ibm.com/developerworks/downloads/r/toolkitforswift/

**Comment by Joannis** [comment]
That must be pretty cool to work with!

**Comment by tnakaike** [comment]
@Joannis I am ready to submit a PR. I also would like to submit PRs to MongoKitten and CryptoKitten. One problem is that CryptoKitten has no license information. Is there any license information for CryptoKitten?

**Comment by Joannis** [comment]
I just added the MIT license to CryptoKitten again. Thanks for the follow-up email. I'm getting back from a long vacation now so I should be more responsive again.

**Comment by Joannis** [comment]
It's hard for me to know how well this works and will keep working on s390x, of course. But they look fine 👍 I'm surprised be how few changes there are

**Comment by tnakaike** [comment]
These are the fixes for current test cases. I am not sure if any other issue exists. If any other issue is found on s390x, I will try to fix it.

Do you need your own tests before merging these changes?

**Comment by Joannis** [comment]
No, I'll merge them soon 👍 I can't run the tests myself.

**Comment by tnakaike** [comment]
Thank you so much!

**Comment by tnakaike** [comment]
Hi @Joannis ,

I have not received any response from Robert for this pull request (https://github.com/OpenKitten/BSON/pull/39). How should we proceed?

**Comment by Obbut** [comment]
@tnakaike I've been on a vacation for the past weeks, sorry. I will have time next friday.
